### PR TITLE
KOGITO-537:Add a new point at kogito-travel-agency tutorial including…

### PR DESCRIPTION
**Pull request by nmirasch**
… keycloak authentication

Added a new 06-kogito-travel-agency-auth point to be able to try the service with security enabled.

### CODE REVIEW

**Comment by nmirasch** [comment]
@mswiderski @cristianonicolai could you take a look on this? Thanks!

**Comment by mswiderski** [comment]
@nmirasch do we have already described how to run all the components to show complete setup?

**Comment by nmirasch** [comment]
@mswiderski I have added a new section 'Architecture' to explain that before the details of each element. Maibe it's more understandable. WDYT?

**Comment by mswiderski** [comment]
@nmirasch looks good to me

so we have to start quite few apps to make it run, right? 
- start Infinispan
- stark Kafka
- start key cloak
- start data index
- start kogito travel agency service
- start visa application service
- start front end app

is this correct?
If so maybe we could provide commands to start them or some scripts, wdyt?

**Comment by nmirasch** [comment]
@mswiderski The commands are there step by step but it's true that there are a lot of steps to perform.
Maybe we can summarize or put them together in scripts,  it would be clearer.
yes, makes sense, let me give a try on that 'magical' :) script Thanks!

**Comment by davidjbrewer** [comment]
At Eupraxia Labs, a Red Hat Common partner, we will participate and contribute where it might be appropriate. I believe one of our folks (senior BPM resource) has already joined this community. We may have two more people (Java) to participate as well. In the near term, we are very interested in the Keycloak integration and would like access to that solution soonest. We protect all of our REST endpoints with Keycloak-based oAuth2.

**Comment by mswiderski** [comment]
@davidjbrewer Kogito already supports keycloak to protect the endpoints, see this example https://github.com/mswiderski/kogito-quickstarts/tree/master/kogito-usertasks-with-security-oidc-keycloak

**Comment by nmirasch** [comment]
@mswiderski I'm going to close this pr regarding the service duplication is not a good option and we will wait until quarkus provide that kind of hibrid auth mechanism that allow work as a service and as a web-app. I redid this auth-doc but the service only works with one of those modes, UI or command line until quarkus provides the fix I prefer to wait.

**Pull request closed without merging**
